-- Shareable invite tokens generated by RAs.
-- One token = access to one reunion.  Tokens remain valid until revoked.
CREATE TABLE reunion_invites (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    reunion_id  UUID        NOT NULL REFERENCES reunions(id) ON DELETE CASCADE,
    token       TEXT        NOT NULL UNIQUE,
    created_by  UUID        NOT NULL REFERENCES users(id),
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reunion_invites_token   ON reunion_invites(token);
CREATE INDEX idx_reunion_invites_reunion ON reunion_invites(reunion_id);

-- Members who joined via an invite link.
-- Gives them direct per-reunion access independent of family-unit assignment.
-- RAs can see this list and assign people to proper family units over time.
CREATE TABLE reunion_invite_members (
    reunion_id  UUID        NOT NULL REFERENCES reunions(id) ON DELETE CASCADE,
    user_id     UUID        NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    invite_id   UUID        NOT NULL REFERENCES reunion_invites(id),
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (reunion_id, user_id)
);

CREATE INDEX idx_rim_user ON reunion_invite_members(user_id);
